<?php
// $Id: views.install,v 1.28 2007-08-12 06:52:14 merlinofchaos Exp $
/**
 * @file views.install
 * Contains install and update functions for Views.
 */
  
function views_install() {
  drupal_set_message('Installing views');
  drupal_install_schema('views');
  db_query("UPDATE {system} SET weight = 10 WHERE name = 'views'");
}

function views_uninstall() {
  drupal_uninstall_schema('views');
}
